#!/usr/bin/python3
import os
from subprocess import CalledProcessError, DEVNULL, check_output
import json
import pprint
def limit_len(string):
    if len(string) > 15:
        return f"{string[:11]}..."
    else: return string
try:
    spotify_status = check_output(["/home/jpeterhaensel/anaconda3/bin/spotify", "status"], stderr=DEVNULL).decode("utf-8").rstrip()
except CalledProcessError as e:
   spotify_status = "Not installed"
except FileNotFoundError as e:
   spotify_status = "Not installed"
try:
    playerctl_status = check_output(["playerctl", "status"], stderr=DEVNULL).decode("utf-8").strip()
except FileNotFoundError:
    playerctl_status = "Not installed"
except CalledProcessError as e:
   playerctl_status = "Not installed"
if spotify_status.split(":",1)[0] == "Playing":
    title = spotify_status.split("\n",1)[0].split(": ",1)[1]
    artist = spotify_status.split("\n")[1].split(" - ",1)[0].strip(" ")
    print(f"{limit_len(title)} | {limit_len(artist)}")
elif playerctl_status == "Playing":
    title = check_output(["playerctl", "metadata","xesam:title"]).decode("utf-8").strip()
    artist = check_output(["playerctl", "metadata","xesam:artist"]).decode("utf-8").strip()
    print(f"{limit_len(title)} | {limit_len(artist)}")
else:
    print(" - | - ")
