#!/bin/bash


if [ "$(playerctl status >>/dev/null 2>&1; echo $?)" == "1" ]
then
	echo "Not Active"
	exit 0
fi
if [ "$(playerctl status)" == "Playing" ]
then
	title=$(playerctl metadata xesam:title)
	artist=$(playerctl metadata xesam:artist)
	if [ ${#title} -gt 15 ]; then
		title="$(echo $title | cut -c -12)..."
	fi
	if [ ${#artist} -gt 15 ]; then
		artist="$(echo $artist | cut -c -12)..."
	fi
	echo "$title | $artist"
else
	echo "Music Stopped"
fi

